global using SharpXcom.Basescape;
global using SharpXcom.Battlescape;
global using SharpXcom.Engine;
global using SharpXcom.Engine.Adlib;
global using SharpXcom.Geoscape;
global using SharpXcom.Interface;
global using SharpXcom.Menu;
global using SharpXcom.Mod;
global using SharpXcom.Savegame;
global using System.Collections.Specialized;
global using System.Diagnostics;
global using System.Globalization;
global using System.Numerics;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Runtime.Intrinsics.X86;
global using System.Text;
global using YamlDotNet.Core;
global using YamlDotNet.Core.Events;
global using YamlDotNet.RepresentationModel;
global using YamlDotNet.Serialization;
global using static SDL2.SDL;
global using static SDL2.SDL_image;
global using static SDL2.SDL_mixer;
global using static SharpXcom.Engine.Adlib.adlplayer;
global using static SharpXcom.Engine.Adlib.fmopl;
global using static SharpXcom.Engine.DosFont;
global using static SharpXcom.Engine.Logger;
global using static SharpXcom.Engine.OpenGL;
global using static SharpXcom.Engine.Shader;
global using static SharpXcom.FMath;
global using static SharpXcom.NativeImports;
global using static SharpXcom.Savegame.SerializationHelper;
global using static SharpXcom.Version;
global using Action = SharpXcom.Engine.Action;
global using Timer = SharpXcom.Engine.Timer;
